[workspace]
pr_branch_prefix = "release/"
pr_draft = true
pr_labels = ["release"]
release_always = true
git_tag_enable = true
git_release_enable = true
git_release_name = "v{{ version }}"
git_tag_name = "v{{ version }}"
